### ISSUE TITLE
Suggestion: Set the margin on body to 0

### ISSUE THREAD

**Issue by jzhu01** [Comicmaniac/colmar_academy#1]
Seen here: https://github.com/Comicmaniac/colmar_academy/blob/631f6a3c94e371cfc59f2003d35b96548aacdea5/index.html#L11

Since body has a default margin of 8px, I recommend setting this to 0 so that you don't have some white borders on your page.

**Comment by Comicmaniac** [comment]
Ah, I thought the reset css took care of this, I'll look into it.
