### ISSUE TITLE
Suggestion - set the video to loop as well

### ISSUE THREAD

**Issue by jzhu01** [Comicmaniac/colmar_academy#2]
Seen here: https://github.com/Comicmaniac/colmar_academy/blob/631f6a3c94e371cfc59f2003d35b96548aacdea5/index.html#L161-L163

Nice job adding a autoplay to your video element! I recommend also adding a `loop` to it as well so that if someone scrolls to the bottom of your page they can still watch the video, even if it has already started.

**Comment by Comicmaniac** [comment]
Good point, added the loop!
